name: Lighthouse

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: "https://nikasproject.ir"
          device: "all"
          gitAuthor: ${{ github.author }}
          gitBranch: ${{ github.ref }}
          gitHubAccessToken: ${{ github.token }}
          locale: "en"
          prCommentEnabled: true
