name: Lighthouse

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: "https://nikasproject.ir"
          device: "all"
          gitAuthor: ${{ github.author }}
          gitBranch: ${{ github.ref }}
          gitHubAccessToken: ${{ github.token }}
          locale: "en"
          prCommentEnabled: true

      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "80"
          minBestPracticesScore: "100"
          minPerformanceScore: "65"
          minProgressiveWebAppScore: "65"
          minSeoScore: "100"
